stages: # 分段
  - install
  # - eslint
  - build
  - deploy
  - notify

cache:
  # untracked: true
  # key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/
    - chat/

install-job:
  tags:
    - develop
  stage: install
  script:
    - echo '安装依赖阶段....'
    - npm install

# eslint-job:
#   tags:
#     - develop
#   stage: eslint
#   script:
#     - npm run eslint

build-job:
  tags:
    - develop
  stage: build
  script:
    - npm run build:test

deploy-job:
  tags:
    - develop
  stage: deploy
  script:
    - whoami
    - sudo rm -rf /home/bizchat_fe/release/bizchat_saas/chat
    - sudo rsync -r ./chat/* /home/bizchat_fe/release/bizchat_saas/chat


# 构建成功时的通知消息
notifySuccessWeChat:
  stage: notify
  script:
    - curl 'http://pushplus.hxtrip.com/send' -H 'Content-Type:application/json' -d "{\"token\":\"130a550e3a6d4dd2a019a98a5c022900\",\"title\":\"微客_前端_聊天工具-部署结果\",\"content\":\"成功\",\"template\":\"html\",\"topic\":\"bizChatFeNotify\"}"
    - curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=6f60f324-9b72-4ad4-b2a9-359fe86812b3' -H 'Content-Type:application/json' -d "{\"msgtype\":\"markdown\",\"markdown\":{\"content\":\"微客_前端_聊天工具-部署结果：<font color=\\"info\\">成功</font>\n>请前往发布平台下载体验\n>本次构建由：$GITLAB_USER_NAME 触发\n>项目名称：$CI_PROJECT_NAME\n>提交号：$CI_COMMIT_SHA\n>提交日志：$CI_COMMIT_MESSAGE\n>构建分支：$CI_COMMIT_BRANCH\n>流水线地址：[$CI_PIPELINE_URL]($CI_PIPELINE_URL)\"}}"
  tags:
    - develop
  when: on_success    

# 构建失败时的通知消息
notifyFailWeChat:
  stage: notify
  script:
    - curl 'http://pushplus.hxtrip.com/send' -H 'Content-Type:application/json' -d "{\"token\":\"130a550e3a6d4dd2a019a98a5c022900\",\"title\":\"微客_前端_聊天工具-部署结果\",\"content\":\"失败\",\"template\":\"html\",\"topic\":\"bizChatFeNotify\"}"
    - curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=6f60f324-9b72-4ad4-b2a9-359fe86812b3' -H 'Content-Type:application/json' -d "{\"msgtype\":\"markdown\",\"markdown\":{\"content\":\"微客_前端_聊天工具-部署结果：<font color=\\"warning\\">失败</font>\n>本次构建由：$GITLAB_USER_NAME 触发\n>项目名称：$CI_PROJECT_NAME\n>提交号：$CI_COMMIT_SHA\n>提交日志：$CI_COMMIT_MESSAGE\n>构建分支：$CI_COMMIT_BRANCH\n>流水线地址：[$CI_PIPELINE_URL]($CI_PIPELINE_URL)\"}}"
  tags:
    - develop
  when: on_failure  

