export const emojiList = [
  { content: '😀' },
  { content: '😃' },
  { content: '😄' },
  { content: '😁' },
  { content: '😆' },
  { content: '😅' },
  { content: '🤣' },
  { content: '😂' },
  { content: '🙂' },
  { content: '🙃' },
  { content: '😉' },
  { content: '😊' },
  { content: '😇' },
  { content: '🥰' },
  { content: '😍' },
  { content: '🤩' },
  { content: '😘' },
  { content: '😗' },
  { content: '😚' },
  { content: '😙' },
  { content: '😋' },
  { content: '😛' },
  { content: '😜' },
  { content: '🤪' },
  { content: '😝' },
  { content: '🤑' },
  { content: '🤗' },
  { content: '🤭' },
  { content: '🤫' },
  { content: '🤔' },
  { content: '🤐' },
  { content: '🤨' },
  { content: '😐' },
  { content: '😑' },
  { content: '😶' },
  { content: '😏' },
  { content: '😒' },
  { content: '🙄' },
  { content: '😬' },
  { content: '🤥' },
  { content: '😌' },
  { content: '😔' },
  { content: '😪' },
  { content: '🤤' },
  { content: '😴' },
  { content: '😷' },
  { content: '🤒' },
  { content: '🤕' },
  { content: '🤢' },
  { content: '🤮' },
  { content: '🤧' },
  { content: '🥵' },
  { content: '🥶' },
  { content: '🥴' },
  { content: '😵' },
  { content: '🤯' },
  { content: '🤠' },
  { content: '🥳' },
  { content: '😎' },
  { content: '🤓' },
  { content: '🧐' },
  { content: '😕' },
  { content: '😟' },
  { content: '🙁' },
  { content: '😮' },
  { content: '😯' },
  { content: '😲' },
  { content: '😳' },
  { content: '🥺' },
  { content: '😦' },
  { content: '😧' },
  { content: '😨' },
  { content: '😰' },
  { content: '😥' },
  { content: '😢' },
  { content: '😭' },
  { content: '😱' },
  { content: '😖' },
  { content: '😣' },
  { content: '😞' },
  { content: '😓' },
  { content: '😩' },
  { content: '😫' },
  { content: '🥱' },
  { content: '😤' },
  { content: '😡' },
  { content: '😠' },
  { content: '🤬' },
  { content: '😈' },
  { content: '👿' },
  { content: '👹' },
  { content: '👺' },
  { content: '🤡' },
  { content: '💀' },
  { content: '💩' },
  { content: '👻' },
  { content: '👽' },
  { content: '👾' },
  { content: '🤖' },
  { content: '😺' },
  { content: '😸' },
  { content: '😹' },
  { content: '😻' },
  { content: '😼' },
  { content: '😽' },
  { content: '🙀' },
  { content: '😿' },
  { content: '😾' },
  { content: '👦' },
  { content: '👧' },
  { content: '👨' },
  { content: '👩' },
  { content: '👴' },
  { content: '👵' },
  { content: '👶' },
  { content: '👱' },
  { content: '👮' },
  { content: '👲' },
  { content: '👳' },
  { content: '👷' },
  { content: '👸' },
  { content: '💂' },
  { content: '🎅' },
  { content: '👰' },
  { content: '👼' },
  { content: '💆' },
  { content: '💇' },
  { content: '🙍' },
  { content: '🙎' },
  { content: '🙅' },
  { content: '🙆' },
  { content: '💁' },
  { content: '🙋' },
  { content: '🙇' },
  { content: '🙌' },
  { content: '🙏' },
  { content: '👤' },
  { content: '👥' },
  { content: '🚶' },
  { content: '🏃' },
  { content: '👯' },
  { content: '💃' },
  { content: '👫' },
  { content: '👬' },
  { content: '👭' },
  { content: '💏' },
  { content: '💑' },
  { content: '👪' },
  { content: '💪' },
  { content: '👈' },
  { content: '👉' },
  { content: '👆' },
  { content: '👇' },
  { content: '✋' },
  { content: '👌' },
  { content: '👍' },
  { content: '👎' },
  { content: '✊' },
  { content: '👊' },
  { content: '👋' },
  { content: '👏' },
  { content: '👐' },
  { content: '👣' },
  { content: '👀' },
  { content: '👂' },
  { content: '👃' },
  { content: '👅' },
  { content: '👄' },
  { content: '💋' },
  { content: '👓' },
  { content: '👔' },
  { content: '👕' },
  { content: '👖' },
  { content: '👗' },
  { content: '👘' },
  { content: '👙' },
  { content: '👚' },
  { content: '👛' },
  { content: '👜' },
  { content: '👝' },
  { content: '🎒' },
  { content: '💼' },
  { content: '👞' },
  { content: '👟' },
  { content: '👠' },
  { content: '👡' },
  { content: '👢' },
  { content: '👑' },
  { content: '👒' },
  { content: '🎩' },
  { content: '🎓' },
  { content: '💄' },
  { content: '💅' },
  { content: '💍' },
  { content: '🌂' },
  { content: '🌹' },
  { content: '🍀' },
  { content: '🍎' },
  { content: '💰' },
  { content: '📱' },
  { content: '🌙' },
  { content: '🍁' },
  { content: '🍂' },
  { content: '🍃' },
  { content: '🌷' },
  { content: '💎' },
  { content: '🔪' },
  { content: '🔫' },
  { content: '🏀' },
  { content: '⚽' },
  { content: '⚾' },
  { content: '🥎' },
  { content: '🏐' },
  { content: '🏈' },
  { content: '🏉' },
  { content: '🎾' },
  { content: '⚡' },
  { content: '👄' },
  { content: '👍' },
  { content: '🔥' },
  { content: '💘' },
  { content: '💝' },
  { content: '💖' },
  { content: '💗' },
  { content: '💓' },
  { content: '💞' },
  { content: '💕' },
  { content: '💟' },
  { content: '❣️' },
  { content: '💔' },
  { content: '❤️' },
  { content: '🧡' },
  { content: '💛' },
  { content: '💚' },
  { content: '💙' },
  { content: '💜' },
  { content: '🤎' },
  { content: '🖤' },
  { content: '🤍' },
  { content: '💯' },
  { content: '💢' }
]

// { name: '微笑' },
// { name: '撇嘴' },
// { name: '色' },
// { name: '发呆' },
// { name: '得意' },
// { name: '流泪' },
// { name: '害羞' },
// { name: '闭嘴' },
// { name: '睡' },
// { name: '大哭' },
// { name: '尴尬' },
// { name: '发怒' },
// { name: '调皮' },
// { name: '呲牙' },
// { name: '惊讶' },
// { name: '难过' },
// { name: '囧' },
// { name: '抓狂' },
// { name: '吐' },
// { name: '偷笑' },
// { name: '愉快' },
// { name: '白眼' },
// { name: '傲慢' },
// { name: '困' },
// { name: '惊恐' },
// { name: '憨笑' },
// { name: '悠闲' },
// { name: '咒骂' },
// { name: '疑问' },
// { name: '嘘' },
// { name: '晕' },
// { name: '衰' },
// { name: '骷髅' },
// { name: '敲打' },
// { name: '再见' },
// { name: '擦汗' },
// { name: '抠鼻' },
// { name: '鼓掌' },
// { name: '坏笑' },
// { name: '右哼哼' },
// { name: '鄙视' },
// { name: '委屈' },
// { name: '快哭了' },
// { name: '阴险' },
// { name: '亲亲' },
// { name: '可怜' },
// { name: '笑脸' },
// { name: '生病' },
// { name: '脸红' },
// { name: '破涕为笑' },
// { name: '恐惧' },
// { name: '失望' },
// { name: '无语' },
// { name: '嘿哈' },
// { name: '捂脸' },
// { name: '奸笑' },
// { name: '机智' },
// { name: '皱眉' },
// { name: '耶' },
// { name: '吃瓜' },
// { name: '加油' },
// { name: '汗' },
// { name: '天啊' },
// { name: 'Emm' },
// { name: '社会社会' },
// { name: '旺柴' },
// { name: '好的' },
// { name: '打脸' },
// { name: '哇' },
// { name: '翻白眼' },
// { name: '666' },
// { name: '让我看看' },
// { name: '叹气' },
// { name: '苦涩' },
// { name: '裂开' },
// { name: '嘴唇' },
// { name: '爱心' },
// { name: '心碎' },
// { name: '拥抱' },
// { name: '强' },
// { name: '弱' },
// { name: '握手' },
// { name: '胜利' },
// { name: '抱拳' },
// { name: '勾引' },
// { name: '拳头' },
// { name: 'OK' },
// { name: '合十' },
// { name: '啤酒' },
// { name: '咖啡' },
// { name: '蛋糕' },
// { name: '玫瑰' },
// { name: '凋谢' },
// { name: '菜刀' },
// { name: '炸弹' },
// { name: '便便' },
// { name: '月亮' },
// { name: '太阳' },
// { name: '庆祝' },
// { name: '礼物' },
// { name: '红包' },
// { name: '發' },
// { name: '福' },
// { name: '烟花' },
// { name: '爆竹' },
// { name: '猪头' },
// { name: '跳跳' },
// { name: '发抖' },
// { name: '转圈' }
export default {}
